import { useState } from "react";
import Head from "next/head";
import {
  UserButton,
  SignInButton,
  SignedIn,
  SignedOut,
  useUser,
} from "@clerk/nextjs";

import { api } from "@/utils/api";
import type { RouterOutputs } from "@/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage, Spinner } from "@/components/spinner";
import toast from "react-hot-toast";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const [input, setInput] = useState("");
  const user = useUser();
  if (!user) return null;

  const { post } = api.useUtils();
  const { mutate, isLoading: isPosting } = api.post.create.useMutation({
    onSuccess: () => {
      setInput("");
      void post.getAll.invalidate();
    },
    onError: (e) => {
      const errorMsg = e.data?.zodError?.fieldErrors.content;
      if (!!errorMsg?.[0]) {
        toast.error(errorMsg[0]);
      } else {
        toast.error("Something went wrong");
      }
    },
  });

  return (
    <>
      <div className="flex flex-row items-center text-3xl">📝</div>
      <input
        type="text"
        placeholder="type some emoji!"
        className="grow bg-gray-900 p-2 text-3xl outline-none"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            if (input !== "") {
              mutate({ content: input });
            }
          }
        }}
        disabled={isPosting}
      />
      {isPosting && (
        <div className="flex items-center justify-center">
          <Spinner size={40} />
        </div>
      )}
      {input !== "" && !isPosting && (
        <button
          className="rounded-md bg-cyan-800 p-2 text-3xl hover:bg-cyan-700"
          onClick={() => mutate({ content: input })}
        >
          📄
        </button>
      )}
    </>
  );
};

type PostWithAuthor = RouterOutputs["post"]["getAll"][number];
const PostView = ({ post, author }: PostWithAuthor) => {
  return (
    <div className="flex gap-4 border-b border-slate-400 p-4" key={post.id}>
      <Image
        src={author.profilePicture}
        alt={`@${author.username}'s profile picture`}
        className="h-10 w-10 rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col ">
        <div className="flex gap-1 text-slate-400">
          <span>{`@${author.username}`}</span>
          <span className="font-thin">{` · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span className="text-2xl">{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.post.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;
  if (!data) return <div>Something went wrong...</div>;

  return (
    <div className="flex flex-col">
      {data.map((fullPost) => (
        <PostView key={fullPost.post.id} {...fullPost} />
      ))}
    </div>
  );
};

export default function Home() {
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <header className="flex gap-4  border-b border-slate-400 p-4">
            <SignedIn>
              {/* Mount the UserButton component */}
              <UserButton
                appearance={{
                  elements: {
                    avatarBox: {
                      width: "3.5rem",
                      height: "3.5rem",
                    },
                  },
                }}
              />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
            {!!data && <CreatePostWizard />}
          </header>
          <Feed />
        </div>
      </main>
    </>
  );
}
