import Head from "next/head";
import { UserButton, SignInButton, SignedIn, SignedOut } from "@clerk/nextjs";

import { api } from "@/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { data } = api.post.getAll.useQuery();

  console.log(data); // Hello from tRPC

  // const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex w-full flex-row items-center justify-end bg-gradient-to-b from-slate-600 to-slate-500 px-4 py-2">
        <SignedIn>
          {/* Mount the UserButton component */}
          <UserButton />
        </SignedIn>
        <SignedOut>
          {/* Signed out users get sign in button */}
          <SignInButton />
        </SignedOut>
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-stone-200">hello twit</h1>
        {data?.map((post) => <div key={post.id}>{post.content}</div>)}
      </main>
    </>
  );
}
